language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - openssl aes-256-cbc -K $encrypted_9e3738e83e33_key -iv $encrypted_9e3738e83e33_iv -in secret_envs.sh.enc -out secret_envs.sh -d

install:
  - composer install

before_script:
  - source secret_envs.sh

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter
